### ISSUE TITLE
Document the curation process for control genotypes

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/canto-docs#5] opened 2021-01-18 16:07 UTC
A while ago we decided that we want to curate all control metagenotypes for both G-f-G and non-G-f-G sessions. The reason for this was to make it clear what the control phenotype was before creating an altered metagenotype. Sometimes it is not clear whether a given phenotype is because of the wild type host genotype being either susceptible or resistant or whether an alteration in the pathogen genotype is responsible for the observation.

Control genotypes will be used in conjunction with AE disease interaction and compared to control (for the altered metagenotype). Also to document on other tickets. #7 #8 

I suggest under 'Creating alleles and genotypes' the text in the screenshot is changed 
![image](https://user-images.githubusercontent.com/11753634/104937224-6a21ad80-59a5-11eb-8b66-4c02c8d329a2.png)
 
suggest this or similar (text edits in **bold**)
Using wild-type alleles in genotypes
A wild-type gene at its normal (endogenous) expression level will generally not have phenotypes annotated in **PHI**-Canto. Single wild-type alleles should only have phenotypes if the gene is expressed at a higher (overexpression) or lower (knockdown) level than normal. Similarly, in a multi-allele genotype, if the wild-type allele is the only allele of the gene present, it should only be included if it is over- or under-expressed.

**However**, it is possible to add a wild-type gene as a single allele with wild-type expression, this is intended only for the case of '**control metagenotypes**' within a pathogen-host interaction: in these cases, a control genotype and phenotype need to be recorded in order to disambiguate naturally-occurring phenotypes (caused by strain sequence variation in the natural strain) from experimental phenotypes (caused by mutations introduced by the author).

![image](https://user-images.githubusercontent.com/11753634/104938292-c6390180-59a6-11eb-9809-949f9906d728.png)
 Suggest new sentence at the end of this text
'A wild-type control metagenotype is created first, followed by a metagenotype containing alterations within either the pathogen genotype, host genotype or both of these to reflect the required pathogen-host interaction experiment.'

**Comment by jseager7** [comment] 2021-01-19 14:41
@CuzickA Here's a draft of the revised text. I went into more detail on the metagenotype management section; please let me know if the terminology is inaccurate.

#### Using wild-type alleles in genotypes

A wild-type gene at its normal (endogenous) expression level will generally not have phenotypes annotated in PHI-Canto. Single wild-type alleles should only have phenotypes if the gene is expressed at a higher (overexpression) or lower (knockdown) level than normal. Similarly, in a multi-allele genotype, if the wild-type allele is the only allele of the gene present, it should only be included if it is over- or under-expressed.

Wild-type genes (as a single allele with wild-type expression) should only be used in a _control metagenotype_ that corresponds to a pathogen-host interaction: in these cases, a control genotype and phenotype need to be recorded in order to disambiguate naturally-occurring phenotypes (caused by strain sequence variation in the natural strain) from experimental phenotypes (caused by mutations introduced by the author).

#### Metagenotype management

To curate a pathogen-host interaction, you should first create a _control metagenotype_, which contains the control genotypes for the pathogen and the host. The control genotypes will usually, but not always, contain wild-type alleles of the genes of interest. After the control metagenotype is created, you should create another metagenotype that describes mutant alleles within either the pathogen genotype, host genotype, or both genotypes simultaneously (the experimental metagenotype can be linked to the control metagenotype by way of an annotation extension, described later).

- - -

We could also link directly to the Curating phenotypes documentation for an explanation of the 'compared to control genotype' annotation extension, rather than just saying it's 'described later', since the explanation isn't actually in the document where this text appears.

**Comment by jseager7** [comment] 2021-01-19 15:10
> 'Wild-type genes (as a single **or multi**-allele with wild-type expression) should only be '

Isn't expression a property of a single allele, rather than a genotype? I know in Canto that every allele is technically a sinlge-allele genotype, but the multi-allele genotypes are made up from single alleles, all with their own expression values.

**Comment by CuzickA** [comment] 2021-01-19 15:13
Oh yes. 
So is it clear enough that a control metagenotype may consist of a pathogen multi-allele genotype in combination with a host?

**Comment by jseager7** [comment] 2021-01-19 15:17
> So is it clear enough that a control metagenotype may consist of a pathogen multi-allele genotype in combination with a host?

Probably not. I'll think about how to make that clearer.

**Comment by jseager7** [comment] 2021-01-19 15:20
I've committed some of the suggested changes, specifically items 2, 3, and 4 of the list above. I'll work on item 1 tomorrow.

**Comment by jseager7** [comment] 2021-01-20 09:57
@CuzickA Here's some draft text for the guidelines about using wild-type genes in PHI-Canto curation. I decided to rewrite the whole section so it doesn't seem like we're giving two sets of guidelines about the same topic:

"Generally speaking, a wild-type gene at its normal (endogenous) expression level should not be annotated with a phenotype unless the gene is expressed at a higher level (overexpression) or lower level (knockdown) than normal. Additionally, wild-type genes with normal expression should not be included in multi-allele genotypes unless they are over- or under-expressed. Wild-type genes with normal expression level may be used in a metagenotype, but only where the metagenotype is used as an experimental control for a pathogen-host interaction (a _control metagenotype_). The control metagenotype, and its corresponding phenotype, are necessary to disambiguate naturally-occurring phenotypes (caused by strain sequence variation in the natural strain) from experimental phenotypes (caused by mutations introduced by the author)."

- - -

The only part I'm not sure about is this:

> Additionally, wild-type genes with normal expression should not be included in multi-allele genotypes unless they are over- or under-expressed.

This is a condensed edit of the following original text, which possibly doesn't have the same meaning:

> Similarly, in a multi-allele genotype, if the wild-type allele is the only allele of the gene present, it should only be included if it is over- or under-expressed.

I changed it because I thought the original text makes it sound like the multi-allele genotype could contain multiple wild-type alleles of the same gene, which doesn't seem very sensible.

**Comment by CuzickA** [comment] 2021-01-20 15:23
Hi @jseager7 I think the text is fine. Two suggestions
i) could we separate it into two paragraphs. The first essentially for single species genotypes and the second for metagenotypes?
ii) perhaps after 'normal expression level' add the actual text used in PHI-Canto in brackets (wild type product level)

**Comment by jseager7** [comment] 2021-01-21 09:58
@CuzickA Here's the amended text (changes in **bold**). I decided to add the wild type product level explanation as a separate sentence at the end, since I thought having it as a parenthetical made the text harder to follow.

- - -

"Generally speaking, a wild-type gene at its normal (endogenous) expression level should not be annotated with a phenotype unless the gene is expressed at a higher level (overexpression) or lower level (knockdown) than normal. Additionally, wild-type genes with normal expression should not be included in multi-allele genotypes unless they are over- or under-expressed.

"Wild-type genes with normal expression level may be used in a metagenotype, but only where the metagenotype is used as an experimental control for a pathogen-host interaction (a control metagenotype). The control metagenotype, and its corresponding phenotype, are necessary to disambiguate naturally-occurring phenotypes (caused by strain sequence variation in the natural strain) from experimental phenotypes (caused by mutations introduced by the author). **Note that in PHI-Canto, the normal expression level is called the 'wild type product level' expression level when creating an allele.**"

**Comment by CuzickA** [comment] 2021-02-01 10:42
@jseager7 This text looks good. 

We can do a final Help text review prior to submitting the PHI-Canto manuscript and any user feedback.

**Comment by jseager7** [comment] 2021-02-01 10:52
@CuzickA Okay, thanks. I've actually already uploaded this text to PHI-Canto, so nothing more needs doing.

**Comment by jseager7** [comment] 2021-02-01 10:52
Note to self: the commit for this change was 7331b4107654737d6ca0f98fb89102e19b5b947f.

**Closed by jseager7** 2021-02-01 10:52 UTC
